# Generated by Django 6.0.7 on 2026-08-03 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=50)),
                ('tax', models.PositiveIntegerField()),
                ('shipping_charges', models.PositiveIntegerField()),
                ('final_amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('CARD', 'Card'), ('CASH ON DELIVERY', 'Cash on Delivery'), ('UPI', 'UPI')], max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('order_status', models.CharField(choices=[('RECIEVED', 'Recieved'), ('OUT_FOR_DELIVERY', 'Out_for_delivery'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
